### ISSUE TITLE
Email Notification Template

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/pillar-webapp#3]
we will default the web app notification strategy to email notification. 

we are working on a way to let user set the frequency of the reminder to pray for a pillar.

the frequency will be daily as the basic unit.

**Comment by calvinckho** [comment]
Hi @AlexTSung, per our discussion, as we will be using email notification as the default reminder mechanism, just a heads up we will be needing template design for the reminder email. So it will be good if you can begin planning this with the designers. thanks!

**Comment by calvinckho** [comment]
Hi @lilymuseum, here are the screenshots of what the email content are included:

There are 4 sections, 3 of which are already implemented: 1) Someone Added You to a Pillar, 2) Pillar Reminder, 3) Someone Left a Comment. The 4th one is "Someone marked this as a praise" and it will be ready soon.

![Screen Shot 2021-07-27 at 6 26 04 PM](https://user-images.githubusercontent.com/23274587/127248848-9857e29f-3008-4bc4-abba-ab8a26316504.png)

![Screen Shot 2021-07-27 at 6 27 17 PM](https://user-images.githubusercontent.com/23274587/127248928-4fd7129f-d501-43ec-9c07-192421341996.png)

**Comment by lilymuseum** [comment]
Hi @calvinckho , in my previous design, users can set reminders and select a specific time for each individual pillar. But, I think it is too complicated, at least in our 1.0 version. Since they will edit through the dashboard settings > notifications, we can remove the "set a reminder" function of the individual pillar. I hope it can simplify the process and keep consistency. What about your thoughts?

Additionally, I suggest adding a "Choose a day" option to the pillar reminder email notifications. E.g. every Tuesday and Friday. I set the "daily" option, and I have been receiving emails every day. I personally feel it is annoying.

**Comment by calvinckho** [comment]
Hi @lilymuseum, IMHO each Pillar's Set Reminder function is still important. The reason is the following: 1) if a user is following 50 pillars, we should let the user pick which of the 50 she wanted to get reminders for (maybe only 5, which are important to her and she wanted to pray for them every M, W, F). 2) In your proposal, if the user follows 50 pillars and there is no way for her to set custom reminders for the 5 pillars that she wants to pray regularly for, then we would need to assume that the user wants to get reminders for all 50, on a M, W, F schedule (for example), which is not very practical. The email notification on M, W, F will be really long (has 50 pillar reminders) and it will render the email digest impractical.

On your second point about the daily email digest, that is only to send out a daily summary email if there is any reminder that the user needs to see. So in the above case, if the 5 pillars each has the reminder set at the M, W, F schedule, then on M, W, F, your email digest would feature them. On the other days, you will not receive an email digest (assuming you also do not have other types of notification for that day). Does that make sense?

**Comment by lilymuseum** [comment]
Hi @calvinckho . Alex and I discussed the pillar email notifications today. We want to simplify the settings. Please let us know your thoughts. @AlexTSung Alex, please let me know if I recap everything correctly. 

Here is a brief Alex created during the sync.
https://docs.google.com/document/d/1EDyQ_os_E4pYciwJaMsfHbKo0HWrr1O-5EPJw9QwEsM/edit
I removed the "Weekly" option because I think it is not necessary at least in the 1.0 version.

In the Global settings, we have 
1. Daily Summary - ON(default) or OFF: 
1.1 If ON, send an email to users at 5 am PST daily to recap everything of the previous day, no need to set a time;
- the daily summary shows sections 2,3,4 (the following) when they are selected as Instant or Daily, 
- any of 2,3,4 selected OFF will be removed from the daily summary
1.2 If OFF, no daily summary (no matter which options select for 2,3,4)

2. Others added to Pillar - Instant(default), Daily, OFF: 
2.1 If instant, send an instant email and shown in daily summary;
2.2 If daily, shown in daily summary;
2.3 If OFF, no email sent, no section in the daily summary

3. Comments: same as “Others added to Pillar.”
4. Mark as Praise: same as “Others added to Pillar.”

Pillar reminder(Time to pray) will be a separate part. It will not be included in the daily summary. Users set pillar reminders on the pillar detail page, choose which time and frequency they want to receive instant notifications of each pillar.

**Comment by calvinckho** [comment]
OK. Yes, it makes sense. I will implement it. I agree let's wait until 2.0 to decide if we want to add the weekly option.

**Comment by calvinckho** [comment]
See latest implementation. Also I improved the language to make the meaning more explicit. Also, I was able to use multi-select in the dropdown, so it is possible to let user customize exactly what they want to be delivered to their inbox.

![Screen Shot 2021-08-05 at 5 11 15 PM](https://user-images.githubusercontent.com/23274587/128436846-42a12759-079c-44f8-84d2-879a603c6652.png)

**Comment by calvinckho** [comment]
Hi @lilymuseum, one more condition that arises is that if Pillar reminder(Time to pray) is turned off globally, we need a way to inform the user when they open the custom pillar reminder modal. See below for my attempt to caution user about it. Your design will be greatly appreciated.

![Screen Shot 2021-08-05 at 5 20 13 PM](https://user-images.githubusercontent.com/23274587/128437485-c41e8e29-43e3-4d33-a81d-d19ff80135e8.png)
